name: WIP Release Workflow

# Configure Manual Trigger
on:
    workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4
              with:  
                token: ${{ secrets.ACTION_GITHUB_TOKEN }}

            - uses: pnpm/action-setup@v3
              with:
                version: 8

            - name: Install Node.js dependencies
              run: pnpm install
      
            - name: build theme
              run: | 
                pnpm run build

            - name: Auto Commit
              uses: stefanzweifel/git-auto-commit-action@v5
              
              with:
                commit_message: 'chore(release): build theme.css'
                file_pattern: '*.css'
                push_options: '--force'


    print:
      runs-on: ubuntu-latest
      steps:
        - name: Check out Git repository
          uses: actions/checkout@v2

        - name: get-npm-version
          id: package-version
          uses: martinbeentjes/npm-get-version-action@v1.3.1


        - name: print version
          run: echo ${{ steps.package-version.outputs.current-version}}
