name: Release

on:
  push:
    branches:
        - "main"


jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
              with:  
                token: ${{ secrets.GITHUB_TOKEN }}

            - uses: pnpm/action-setup@v3
              with:
                version: 8

            - name: install deps
              run: pnpm install
      
            - name: build
              run: | 
                pnpm run build

            - name: gen release
              run: pnpm exec semantic-release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
