name: Release

on:
  push:
    branches:
      - stable


jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4
              with:  
                token: ${{ secrets.ACTION_GITHUB_TOKEN }}

            - uses: pnpm/action-setup@v3
              with:
                version: 8

            - name: Install Node.js dependencies
              run: pnpm install
      
            - name: build theme
              run: | 
                pnpm run build

            - name: Auto Commit
              uses: stefanzweifel/git-auto-commit-action@v5
              
              with:
                commit_message: 'chore(release): build theme.css'
                file_pattern: '*.css'
                push_options: '--force'
            
            - name: Bump Version
              run: |
              pnpm version
              git push --tags

            - name: Get New Version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@v1.3.1

            - name: Print new Version
              run: echo ${{ steps.package-version.outputs.current-version}}

            - name: bundle folder
            - run: |
              mkdir Nordic
              cp manifest.json theme.css Nordic/
              zip -r Nordic.zip Nordic/


            - uses: ncipollo/release-action@v1
              with:
                artifacts: "manifest.json, theme.css, Nordic.zip"
                makeLatest: true
                tag: ${{ steps.package-version.outputs.current-version}}
                generateReleaseNotes: true
