name: WIP Release Workflow

# Configure Manual Trigger
on:
    workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - uses: pnpm/action-setup@v3
              with:
                version: 8

            - name: Install Node.js dependencies
              run: pnpm install
      
            - name: build theme
              run: pnpm run build

            - uses: actions/checkout@v3
            - name: bump version
              run: pnpm version patch
            - name: Commit report
              run: |
                git config --global user.name 'Nato'
                git config --global user.email 'natowb@users.noreply.github.com'
                git commit -am "Automated version push"
                git push
                git push --tags

    print:
      runs-on: ubuntu-latest
      steps:
        - name: Check out Git repository
          uses: actions/checkout@v2

        - name: get-npm-version
          id: package-version
          uses: martinbeentjes/npm-get-version-action@v1.3.1

        - name: print version
          run: echo ${{ steps.package-version.outputs.current-version}}





